# Generated by Django 4.2.5 on 2023-09-25 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(max_length=5, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.CharField(max_length=2, verbose_name='Версия'),
        ),
    ]
