# Generated by Django 4.2.5 on 2023-09-25 14:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_alter_robot_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[django.core.validators.MaxValueValidator(datetime.datetime(2023, 9, 25, 17, 52, 36, 597012))], verbose_name='Создан'),
        ),
    ]
